---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: $MOLECULE_ROLE_IMAGE
    dockerfile: ../../tests/molecule/Dockerfile-noprivs.j2
    command: "/lib/systemd/systemd"
    privileged: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    groups:
      - database
      - activemq
      - transformers
      - indexers
      - elasticsearch
      - repository
      - trusted_resource_consumers
      - acc
      - nginx
    published_ports:
      - 0.0.0.0:443:443/tcp
      - 0.0.0.0:9200:9200/tcp

provisioner:
  name: ansible
  config_options:
    defaults:
      pipelining: true
  ansible_args:
    - -e
    - "acs_play_repository_acs_edition=Community"
  inventory:
    links:
      host_vars: host_vars
  playbooks:
    prepare: ../default/prepare.yml
    verify: verify.yml
verifier:
  name: ansible
