---
- name: Verify repository is configured for Solr indexing
  hosts: repository
  gather_facts: false
  tasks:
    - name: Read contents of alfresco-global.properties
      become: true
      ansible.builtin.slurp:
        src: /etc/opt/alfresco/content-services/classpath/alfresco-global.properties
      register: global_props_raw

    - name: Assert Solr subsystem is configured with shared secret auth
      vars:
        global_props: "{{ global_props_raw.content | b64decode }}"
      ansible.builtin.assert:
        that:
          - "'index.subsystem.name=solr6' in global_props"
          - "'solr.secureComms=secret' in global_props"
        fail_msg: "Solr subsystem or solr.secureComms not configured in alfresco-global.properties"

    - name: Read tomcat.sh
      become: true
      ansible.builtin.slurp:
        src: /opt/alfresco/tomcat.sh
      register: tomcat_sh_raw

    - name: Assert the repository is configured with the tracking shared secret
      ansible.builtin.assert:
        that:
          - "'-Dsolr.sharedSecret=' in (tomcat_sh_raw.content | b64decode)"
        fail_msg: "-Dsolr.sharedSecret not found in tomcat.sh"

- name: Import the default verify playbook
  ansible.builtin.import_playbook: ../default/verify.yml
