---
- name: Prepare remote hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Make sure python3 is installed
      package:
        name: python3
        state: present
      become: true

    - name: Check for apt
      ansible.builtin.stat:
        path: /usr/bin/apt-get
      register: apt_get

    - name: Upgrade all packages (Debian/Ubuntu)
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      become: true
      when: apt_get.stat.exists

    - name: Upgrade all packages (RHEL/Rocky)
      ansible.builtin.dnf:
        name: '*'
        state: latest
        exclude:
          - rocky-release*
          - rocky-repos*
          - rocky-gpg-keys*
          - redhat-release*
      become: true
      when: not apt_get.stat.exists
