---
- name: Converge
  hosts: all
  vars:
    molecule_nexus_username: "{{ lookup('env', 'NEXUS_USERNAME') }}"
    molecule_nexus_password: "{{ lookup('env', 'NEXUS_PASSWORD') }}"
  roles:
    - role: activemq
    - role: postgres
  tasks:
    - name: Setup sync database
      ansible.builtin.include_role:
        name: postgres
        tasks_from: setup_db
      vars:
        postgres_db_name: "{{ sync_db_name }}"
        postgres_db_username: "{{ sync_db_username }}"
        postgres_db_password: "{{ sync_db_password }}"
        postgres_db_clients: "{{ groups.syncservice }}"
    - name: Install Alfresco sync service
      ansible.builtin.include_role:
        name: sync
      vars:
        sync_repo_config_url: "https://run.mocky.io/v3/a62ce156-37c8-47b3-8cd1-08628b3aa130"
        sync_zip_username: "{{ molecule_nexus_username }}"
        sync_zip_password: "{{ molecule_nexus_password }}"
        sync_environment:
          JAVA_OPTS:
            - -Xms512m
            - -Xmx900m
