---
- name: Converge
  hosts: all
  tasks:
    - name: "Include activemq"
      ansible.builtin.include_role:
        name: "activemq"
    - name: Flush Handlers
      ansible.builtin.meta: flush_handlers
    - name: "Include transformers"
      ansible.builtin.include_role:
        name: "transformers"
      vars:
        transformers_tengine_environment:
          JAVA_OPTS:
            - -Xms512m
            - -Xmx900m
        transformers_libreoffice_repository: "{{ acs_play_transformers_libreoffice_repository }}"
        transformers_pdf_repository: "{{ acs_play_transformers_pdf_repository }}"
        transformers_imagemagick_repository: "{{ acs_play_transformers_imagemagick_repository }}"
        transformers_aio_repository: "{{ acs_play_transformers_aio_repository }}"
