---
# handlers file for search_enterprise
- name: Enable elasticsearch-connector service
  become: true
  ansible.builtin.service:
    name: elasticsearch-connector
    enabled: true
    daemon_reload: true

- name: Restart elasticsearch-connector service
  become: true
  ansible.builtin.service:
    name: elasticsearch-connector
    state: restarted
    daemon_reload: true

- name: Run elasticsearch-connector reindex service
  become: true
  when: search_enterprise_repo_db_url | length > 0
  ansible.builtin.systemd:
    name: elasticsearch-connector-reindex
    state: started
    daemon_reload: true
