# Forked from https://github.com/ansible-community/molecule-docker/blob/main/src/molecule_docker/playbooks/Dockerfile.j2

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN if [ $(command -v apt-get) ]; then export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y python3 sudo bash ca-certificates iproute2 python3-apt aptitude systemd curl && apt-get clean && rm -rf /var/lib/apt/lists/* && touch -t 2201010000 /var/lib/apt/lists/; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install /usr/bin/python3 /usr/bin/python3-config /usr/bin/dnf-3 sudo bash iproute procps-ng systemd initscripts && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y /usr/bin/python /usr/bin/python2-config sudo yum-plugin-ovl bash iproute systemd initscripts && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python3 sudo bash iproute2 && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python3 sudo bash ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python3 sudo bash ca-certificates iproute2 && xbps-remove -O; fi

RUN set -xe \
  && DEPLOY_USER=ansible DEPLOY_GROUP=deployer \
  && [ -f /etc/debian_version ] && SUDO_GROUP=sudo || SUDO_GROUP=wheel \
  && groupadd -r ${DEPLOY_GROUP} \
  && useradd -m -g ${DEPLOY_GROUP} ${DEPLOY_USER} \
  && usermod -aG ${SUDO_GROUP} ${DEPLOY_USER} \
  && sed -i "/^%${SUDO_GROUP}/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers
