MOLECULE_IT_IMAGE_ID: ami-05e9d272e4355d35c # RHEL-8.10.0_HVM-20260318-x86_64-2090-Hourly2-GP3
MOLECULE_IT_EXTRA_VARS: acs_play_major_version=25
MOLECULE_IT_TEST_CONFIG: tests/test-config-25.json
MOLECULE_IT_PLATFORM: rhel8
