---
- name: Converge
  hosts: all
  roles:
    - role: activemq
    - role: elasticsearch
      vars:
        elasticsearch_major_version: '7.x'
    - role: audit_storage
      vars:
        audit_storage_zip_url: >-
          {{ acs_play_audit_storage_repository }}/{{ acs_play_audit_storage_artifact_name }}/{{ audit_storage_version }}/{{ acs_play_audit_storage_artifact_name }}-{{ audit_storage_version }}.zip
        audit_storage_zip_checksum: "sha1:{{ audit_storage_zip_url }}.sha1"
