---
# defaults file for roles/transformers
pkg_format: "{% if ansible_pkg_mgr == 'apt' %}deb{% else %}rpm{% endif %}"
tengine_environment:
  JAVA_OPTS:
    - -Xms512m
    - -Xmx1536m
ats_keystore: {}
include_ghostscript: false

transformers_imagemagick_version: 7.1.0-16-ci-11
transformers_imagemagick_repository: https://artifacts.alfresco.com/nexus/content/groups/public/org/alfresco
