name: setup-python
description: Install python from .python-version file and cache with pipenv
outputs:
  python-version:
    description: "The python version that was installed"
    value: ${{ steps.setup-python.outputs.python-version }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      id: setup-python
      with:
        python-version-file: '.python-version'
        cache: 'pipenv'
