name: setup-python
description: Install python from .python-version file and cache with pipenv
outputs:
  python-version:
    description: "The python version that was installed"
    value: ${{ steps.setup-python.outputs.python-version }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      id: setup-python
      with:
        python-version-file: '.python-version'
        cache: 'pipenv'
