all:
  children:
    external:
      children:
        external_activemq:
          hosts:
            b-b756e498-0b59-42e7-8b5e-7f7470af127b-1.mq.eu-west-1.amazonaws.com:
              {activemq_port: 61617, activemq_transport: ssl, activemq_username: alfresco}

        external_elasticsearch:
          hosts:
            vpc-molecule1multimachine111loca-t4inhtzhfyx7moja2cjmkkv5ua.eu-west-1.es.amazonaws.com:
              {elasticsearch_auth_mode: aws-iam, elasticsearch_aws_region: eu-west-1, elasticsearch_port: 443,
  elasticsearch_protocol: https}
