MOLECULE_IT_IMAGE_ID: ami-009711326e3ed7468 # RHEL-9.7.0_HVM-20260303-x86_64-0-Hourly2-GP3
MOLECULE_IT_EXTRA_VARS: acs_play_major_version=26
MOLECULE_IT_TEST_CONFIG: tests/test-config.json
MOLECULE_IT_PLATFORM: multimachine
