---
# This playbook is used to run preliminary upgrade checks for the hosts in the ACS deployment.
- name: Include vars based on acs major version
  ansible.builtin.import_playbook: include-vars.yml

- name: Run preliminary upgrade checks for all hosts
  hosts: all:!external
  gather_facts: false
  tasks:
    - name: Fetch status file with installed versions
      ansible.builtin.fetch:
        src: "{{ ansible_installation_status_file }}"
        fail_on_missing: false
        dest: /tmp/
      register: ansible_components_status
      changed_when: false

    - name: Read installed versions from status file when available
      ansible.builtin.include_vars:
        file: /tmp/{{ inventory_hostname }}/{{ ansible_installation_status_file }}
        name: installed_components
      when: ansible_components_status.msg is undefined

    - name: Check for unsupported components upgrades
      any_errors_fatal: true
      module_defaults:
        ansible.builtin.fail:
          msg: >
            You're trying to upgrade in an unsupported manner!
            Please read our documentation for more informations on what's supported and what isn't.
            https://github.com/Alfresco/alfresco-ansible-deployment/blob/master/docs/components-upgrade.md
      vars:
        is_cal_major_version: "{{ acs_play_repository_acs_version.split('.')[0] | int >= 23 }}"
        semver_patch_slice_length: 2
        acs_version_slice_length: "{{ semver_patch_slice_length if is_cal_major_version else 3 }}"
      block:
        - name: Fail on unsupported ACS upgrade
          ansible.builtin.fail:
          when:
            - installed_components.acs is defined
            - |
              acs_play_repository_acs_version.split('.')[:acs_version_slice_length] | join('.') != installed_components.acs.version.split('.')[:acs_version_slice_length] | join('.') or
              acs_play_repository_acs_version is version(installed_components.acs.version, 'lt')

        - name: Initialize evaluation of currently installed amps
          ansible.builtin.set_fact:
            amps: {}

        - name: Add common amps
          ansible.builtin.set_fact:
            amps: >-
              {{ amps | combine({
                'aos_module': {
                  'version': acs_play_repository_amp_aos_module_version
                },
                'googledrive_repo': {
                  'version': acs_play_repository_amp_googledrive_repo_version
                },
                'googledrive_share': {
                  'version': acs_play_repository_amp_googledrive_share_version
                }
              }) }}

        - name: Add device sync amp
          ansible.builtin.set_fact:
            amps: >-
              {{ amps | combine({
                'device_sync': {
                  'version': acs_play_repository_amp_device_sync_version
                }
              }) }}
          when: acs_play_repository_acs_edition == 'Enterprise'

        - name: Fail on unsupported AMPS upgrades
          ansible.builtin.fail:
          when:
            - installed_components is defined
            - installed_components.amps is defined
            - item in amps
            - |
              amps[item].version.split('.')[:semver_patch_slice_length] | join('.') != installed_components.amps[item].version.split('.')[:semver_patch_slice_length] | join('.') or
              amps[item].version is version(installed_components.amps[item].version, 'lt')
          loop: "{{ installed_components.amps | list }}"

        - name: Fail on unsupported Transformers upgrades
          ansible.builtin.fail:
          when:
            - installed_components.transform is defined
            - |
              acs_play_transformers_aio_version.split('.')[0] != installed_components.transform.version.split('.')[0] or
              acs_play_transformers_aio_version is version(installed_components.transform.version, 'lt')

        - name: Fail on unsupported Trouter upgrades
          ansible.builtin.fail:
          when:
            - installed_components.trouter is defined
            - |
              acs_play_trouter_version.split('.')[:semver_patch_slice_length] | join('.') != installed_components.trouter.version.split('.')[:semver_patch_slice_length] | join('.') or
              acs_play_trouter_version is version(installed_components.trouter.version, 'lt')

        - name: Fail on unsupported SFS upgrades
          ansible.builtin.fail:
          when:
            - installed_components.sfs is defined
            - |
              acs_play_sfs_version.split('.')[:semver_patch_slice_length] | join('.') != installed_components.sfs.version.split('.')[:semver_patch_slice_length] | join('.') or
              acs_play_sfs_version is version(installed_components.sfs.version, 'lt')

        - name: Fail on unsupported Search upgrades
          ansible.builtin.fail:
          when:
            - installed_components.search is defined
            - |
              acs_play_search_version.split('.')[:semver_patch_slice_length] | join('.') != installed_components.search.version.split('.')[:semver_patch_slice_length] | join('.') or
              acs_play_search_version is version(installed_components.search.version, 'lt')
