name: Release → Jira

on:
  release:
    types: [published]

jobs:
  propagate-release:
    runs-on: ubuntu-slim
    steps:
      - name: Propagate Jira release
        uses: Alfresco/alfresco-build-tools/.github/actions/jira-propagate-release@v17.6.1
        with:
          jira-url: ${{ vars.JIRA_URL }}
          jira-project-key: "OPSEXP"
          jira-user: ${{ vars.JIRA_USER }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          merge-versions: "true"
          github-version-prefix: "v"
          jira-version-prefix: "Ansible Playbooks "
