name: Publish docs

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"
      - .github/workflows/docs.yml
  pull_request:
    branches:
      - master
    paths:
      - "docs/**"
      - .github/workflows/docs.yml

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    uses: Alfresco/jekyll-build-tools/.github/workflows/jekyll-publish.yml@a821305960121ffa2b4bdb0047786a8d3c220481 # v0.4.0
    with:
      working-directory: docs
      publish: ${{ github.event_name == 'push' && github.ref_name == 'master' }}
      validate-html: true
      validate-html-args: --ignore-urls "/linux.die.net/,https://www.vagrantup.com/downloads"
