name: kics

on:
  pull_request:
    branches:
      - master
      - 'next/**'
    paths:
      - 'playbooks/**'
      - 'roles/**'
      - '.github/workflows/kics.yml'
  push:
    branches: [master]
    paths:
      - 'playbooks/**'
      - 'roles/**'
      - '.github/workflows/kics.yml'

permissions:
  security-events: write

jobs:
  kics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run KICS Scan
        uses: checkmarx/kics-github-action@05aa5eb70eede1355220f4ca5238d96b397e30a6 # v2.1.20
        with:
          path: 'playbooks,roles'
          ignore_on_exit: results
          output_path: report-dir/
          output_formats: 'sarif'
          token: ${{ secrets.GITHUB_TOKEN }}
          enable_jobs_summary: true
          platform_type: ansible
          disable_secrets: true
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@e46ed2cbd01164d986452f91f178727624ae40d7 # v4.35.3
        with:
          sarif_file: report-dir/results.sarif
