name: "release"
on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Get tag name
        shell: bash
        run: |
          if [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            VERSION="${GITHUB_REF##*/v}"
          else
            VERSION="0.0.0"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Generate Ansible playbook v${{ env.VERSION }}
        run: |
          ./scripts/generate-zip.sh

      - name: Publish to S3 release bucket
        if: github.event_name != 'workflow_dispatch'
        uses: Alfresco/alfresco-build-tools/.github/actions/s3-upload@v19.2.1
        with:
          aws-region: ${{ vars.AWS_RELEASE_ARTIFACT_UPLOAD_REGION }}
          aws-role-arn: ${{ vars.AWS_RELEASE_ARTIFACT_UPLOAD_ROLE_ARN }}
          source: alfresco-ansible-deployment-${{ env.VERSION }}.zip
          destination: s3://${{ vars.AWS_RELEASE_ARTIFACT_UPLOAD_BUCKET }}/release/enterprise/alfresco-ansible-deployment/

      - name: Publish on Nexus
        uses: Alfresco/alfresco-build-tools/.github/actions/maven-deploy-file@v19.2.1
        if: github.event_name != 'workflow_dispatch'
        with:
          group-id: org.alfresco
          artifact-id: alfresco-ansible-deployment
          repository-url: https://nexus.alfresco.com/nexus/content/repositories/releases/
          version: ${{ env.VERSION }}
          file: alfresco-ansible-deployment-${{ env.VERSION }}.zip
          classifier: zip
          maven-username: ${{ secrets.nexus_username }}
          maven-password: ${{ secrets.nexus_password }}
