@startuml

Title: WIP - ACS High Availability Deployment

' NOTE: This is still Work In Progress

skinparam componentStyle uml2
skinparam linetype ortho
skinparam rectangle {
    BorderStyle dashed
}

actor Client

node "ingress" as ingressnode #lightgrey {
    component "NGINX Proxy" as proxy #4d9cea
    component "Control Center" as acc #4d9cea
    component "Digital Workspace" as adw #4d9cea
}

rectangle {
    node "repository-lb" as repolbnode #lightgrey {
        component "NGINX Proxy" as repolb #4d9cea
    }

    node "repository1" as reponode1 #lightgrey {
        component "Repository" as repo1 #4d9cea
        component "Share" as share1 #4d9cea
        component "Tomcat" as tomcat1  #4d9cea
        component "Java" as repojava1 #4d9cea
    }

    node "repository2" as reponode2 #lightgrey {
        component "Repository" as repo2 #4d9cea
        component "Share" as share2 #4d9cea
        component "Tomcat" as tomcat2  #4d9cea
        component "Java" as repojava2 #4d9cea
    }
}

rectangle {
    node "search-lb" as searchlbnode #lightgrey {
        component "NGINX Proxy" as searchlb #4d9cea
    }

    node "search1" as searchnode1 #lightgrey {
        component "Search Service" as search1 #4d9cea
        component "Java" as searchjava1 #4d9cea
    }

    node "search2" as searchnode2 #lightgrey {
        component "Search Service" as search2 #4d9cea
        component "Java" as searchjava2 #4d9cea
    }
}

rectangle {
    node "transform-lb" as transformlbnode #lightgrey {
        component "NGINX Proxy" as transformlb #4d9cea
    }

    node "transform1" as transformnode1 #lightgrey {
        component "Transform (Router, SFS & AIO)" as transform1 #4d9cea
        component "Java" as transformjava1 #4d9cea
    }

    node "transform2" as transformnode2 #lightgrey {
        component "Transform (Router, SFS & AIO)" as transform2 #4d9cea
        component "Java" as transformjava2 #4d9cea
    }
}

rectangle {
    node "sync-lb" as synclbnode #lightgrey {
        component "NGINX Proxy" as synclb #4d9cea
    }

    node "sync1" as syncnode1 #lightgrey {
        component "Sync Service" as sync1 #4d9cea
        component "Java" as syncjava1 #4d9cea
    }

    node "sync2" as syncnode2 #lightgrey {
        component "Sync Service" as sync2 #4d9cea
        component "Java" as syncjava2 #4d9cea
    }
}

database "ActiveMQ" as amq
database "PostgreSQL" as psql
storage "NFS" as nfs

note top of repolb
This is a single point of failure
so customers may wish to replace
this with Nginx Plus and use its
HA features.
end note

note top of searchlb
This is a single point of failure
so customers may wish to replace
this with Nginx Plus and use its
HA features.
end note

note top of transformlb
This is a single point of failure
so customers may wish to replace
this with Nginx Plus and use its
HA features.
end note

note top of synclb
This is a single point of failure
so customers may wish to replace
this with Nginx Plus and use its
HA features.
end note

acc .. proxy
adw .. proxy
repo1 .. tomcat1
share1 .. tomcat1
tomcat1 .. repojava1
repo2 .. tomcat2
share2 .. tomcat2
tomcat2 .. repojava2
search1 .. searchjava1
search2 .. searchjava2
transform1 .. transformjava1
transform2 .. transformjava2
sync1 .. syncjava1
sync2 .. syncjava2

Client --> proxy

proxy --> repolb
proxy --> acc
proxy --> adw

repolb -down-> repo1
repolb -down-> repo2
repolb -down-> share1
repolb -down-> share2
searchlb -down-> search1
searchlb -down-> search2
transformlb -down-> transform1
transformlb -down-> transform2
synclb -down-> sync1
synclb -down-> sync2

share1 --> repolb
share2 --> repolb
acc --> repolb
adw --> repolb

repo1 --> psql
repo2 --> psql
repo1 --> amq
repo2 --> amq

repo1 --> transformlb
repo2 --> transformlb

repo1 --> searchlb
repo2 --> searchlb
search1 --> repolb
search2 --> repolb

repo1 --> synclb
repo2 --> synclb
sync1 --> repolb
sync2 --> repolb

transform1 --> amq
transform2 --> amq

sync1 --> amq
sync2 --> amq
sync1 --> psql
sync2 --> psql
repo1 --> nfs
repo2 --> nfs
transform1 --> nfs
transform2 --> nfs

center footer Copyright 2020 Alfresco Software Inc

@enduml
