@startuml

Title: WIP - ACS High Availability Deployment

' NOTE: This is still Work In Progress

skinparam componentStyle uml2
skinparam linetype ortho
skinparam rectangle {
    BorderStyle dashed
}

actor Client

node "ingress" as ingressnode #lightgrey {
    component "NGINX Proxy" as proxy #4d9cea
    component "Digital Workspace" as adw #4d9cea
}

rectangle {
    node "repository-lb" as repolbnode #lightgrey {
        component "NGINX Proxy" as repolb #4d9cea
    }

    node "repository1" as reponode1 #lightgrey {
        component "Repository" as repo1 #4d9cea
        component "Share" as share1 #4d9cea
        component "Tomcat" as tomcat1  #4d9cea
        component "Java" as repojava1 #4d9cea
    }

    node "repository2" as reponode2 #lightgrey {
        component "Repository" as repo2 #4d9cea
        component "Share" as share2 #4d9cea
        component "Tomcat" as tomcat2  #4d9cea
        component "Java" as repojava2 #4d9cea
    }
}

rectangle {
    node "search-lb" as searchlbnode #lightgrey {
        component "NGINX Proxy" as searchlb #4d9cea
    }

    node "search1" as searchnode1 #lightgrey {
        component "Search Service" as search1 #4d9cea
        component "Java" as searchjava1 #4d9cea
    }

    node "search2" as searchnode2 #lightgrey {
        component "Search Service" as search2 #4d9cea
        component "Java" as searchjava2 #4d9cea
    }
}

rectangle {
    node "transformrouter-lb" as transformrouterlbnode #lightgrey {
        component "NGINX Proxy" as transformrouterlb #4d9cea
    }

    node "transform-router1" as transformrouternode1 #lightgrey {
        component "Transform (Router & SFS)" as transformrouter1 #4d9cea
        component "Java" as transformrouterjava1 #4d9cea
    }

    node "transform-router2" as transformrouternode2 #lightgrey {
        component "Transform (Router & SFS)" as transformrouter2 #4d9cea
        component "Java" as transformrouterjava2 #4d9cea
    }

    node "transformengine-lb" as transformenginelbnode #lightgrey {
        component "NGINX Proxy" as transformenginelb #4d9cea
    }

    node "transform-engine1" as transformenginenode1 #lightgrey {
        component "Transform (T-Engine)" as transformengine1 #4d9cea
        component "Java" as transformenginejava1 #4d9cea
    }

    node "transform-engine2" as transformenginenode2 #lightgrey {
        component "Transform (T-Engine)" as transformengine2 #4d9cea
        component "Java" as transformenginejava2 #4d9cea
    }
}

rectangle {
    node "sync-lb" as synclbnode #lightgrey {
        component "NGINX Proxy" as synclb #4d9cea
    }

    node "sync1" as syncnode1 #lightgrey {
        component "Sync Service" as sync1 #4d9cea
        component "Java" as syncjava1 #4d9cea
    }

    node "sync2" as syncnode2 #lightgrey {
        component "Sync Service" as sync2 #4d9cea
        component "Java" as syncjava2 #4d9cea
    }
}

database "ActiveMQ" as amq
database "PostgreSQL" as psql

adw .. proxy
repo1 .. tomcat1
share1 .. tomcat1
tomcat1 .. repojava1
repo2 .. tomcat2
share2 .. tomcat2
tomcat2 .. repojava2
search1 .. searchjava1
search2 .. searchjava2
transformrouter1 .. transformrouterjava1
transformrouter2 .. transformrouterjava2
transformengine1 .. transformenginejava1
transformengine2 .. transformenginejava2
sync1 .. syncjava1
sync2 .. syncjava2

Client --> proxy

proxy --> repolb
proxy --> adw

repolb -down-> repo1
repolb -down-> repo2
repolb -down-> share1
repolb -down-> share2
searchlb -down-> search1
searchlb -down-> search2
transformrouterlb -down-> transformrouter1
transformrouterlb -down-> transformrouter2
transformrouter1 -down-> transformenginelb
transformrouter2 -down-> transformenginelb
transformenginelb -down-> transformengine1
transformenginelb -down-> transformengine2
synclb -down-> sync1
synclb -down-> sync2

share1 --> repolb
share2 --> repolb
adw --> repolb

repo1 --> psql
repo2 --> psql
repo1 --> amq
repo2 --> amq

repo1 --> transformrouterlb
repo2 --> transformrouterlb

repo1 --> searchlb
repo2 --> searchlb
search1 --> repolb
search2 --> repolb

repo1 --> synclb
repo2 --> synclb
sync1 --> repolb
sync2 --> repolb

transformrouter1 --> amq
transformrouter2 --> amq

sync1 --> amq
sync2 --> amq
sync1 --> psql
sync2 --> psql

center footer Copyright 2020 Alfresco Software Inc

@enduml
