@startuml acs-multi-machine

skinparam componentStyle uml2
skinparam linetype ortho

actor User

node "Control Node" as "control" #LightGrey {
    rectangle "Playbook" as playbook #Ivory

    rectangle "inventory" #White
}

node "nginx" as nginxnode #lightgrey {
    component "NGINX Proxy" as proxy #4d9cea
    component "Common" as nginxcommon #4d9cea
}

node "acc" as accnode #lightgrey {
    component "Control Center" as acc #4d9cea
    component "Common" as acccommon #4d9cea
}

node "adw" as adwnode #lightgrey {
    component "Digital Workspace" as adw #4d9cea
    component "Common" as adwcommon #4d9cea
}

node "repository" as reponode #lightgrey {
    component "Repository & Share" as repo #4d9cea
    component "Tomcat" as tomcat  #4d9cea
    component "Java" as repojava #4d9cea
    component "Common" as repocommon #4d9cea
}

node "search" as searchnode #lightgrey {
    component "Search Service" as search #4d9cea
    component "Java" as searchjava #4d9cea
    component "Common" as searchcommon #4d9cea
}

node "transform" as transformnode #lightgrey {
    component "AIO Transform Engine" as tengine #4d9cea
    component "Transform Router" as trouter #4d9cea
    component "Shared File Service" as sfs #4d9cea
    component "Java" as transformjava #4d9cea
    component "Common" as transformcommon #4d9cea
}

node "sync" as syncnode #lightgrey {
    component "Sync Service" as sync #4d9cea
    component "Java" as syncjava #4d9cea
    component "Common" as synccommon #4d9cea
}

node "activemq" as amqnode #lightgrey {
    component "ActiveMQ" as amq #4d9cea
    component "Java" as amqjava #4d9cea
    component "Common" as amqcommon #4d9cea
}

node "database" as dbnode #lightgrey {
    component "PostgreSQL" as psql #4d9cea
    component "Common" as dbcommon #4d9cea
}

User -> playbook
playbook <- inventory

playbook -down-> psql
playbook -down-> amq
playbook -down-> tengine
playbook -down-> search
playbook -down-> repo
playbook -down-> trouter
playbook -down-> sfs
playbook -down-> sync
playbook -down-> proxy
playbook -down-> acc
playbook -down-> adw

amq .down.> amqjava
acc .down.> acccommon
adw .down.> adwcommon
proxy .down.> nginxcommon
psql .down.> dbcommon
repo .down.> tomcat
search .down.> searchjava
sfs .down.> transformjava
sync .down.> syncjava
tomcat .down.> repojava
tengine .down.> transformjava
trouter .down.> transformjava

amqjava .down.> amqcommon
searchjava .down.> searchcommon
transformjava .down.> transformcommon
syncjava .down.> synccommon
repojava .down.> repocommon

center footer Copyright 2020 Alfresco Software Inc

@enduml
