@startuml

Title: ACS Multi Machine Deployment

skinparam componentStyle uml2
skinparam linetype ortho
skinparam rectangle {
    BorderStyle dashed
}

actor Client

node "ingress" as ingressnode #lightgrey {
    component "NGINX Proxy" as proxy #4d9cea
    component "Digital Workspace" as adw #4d9cea
}

node "repository" as reponode #lightgrey {
    component "Repository" as repo #4d9cea
    component "Share" as share #4d9cea
    component "Tomcat" as tomcat  #4d9cea
    component "Java" as repojava #4d9cea
}

node "search" as searchnode #lightgrey {
    component "Search Service" as search #4d9cea
    component "Java" as searchjava #4d9cea
}

node "transform" as transformnode #lightgrey {
    component "Transform (Router, SFS & AIO)" as transform #4d9cea
    component "Java" as transformjava #4d9cea
}

node "sync" as syncnode #lightgrey {
    component "Sync Service" as sync #4d9cea
    component "Java" as syncjava #4d9cea
}

node "activemq" as amqnode #lightgrey {
    component "ActiveMQ" as amq #4d9cea
    component "Java" as amqjava #4d9cea
}

node "database" as dbnode #lightgrey {
    component "PostgreSQL" as psql #4d9cea
}

adw .. proxy
repo .. tomcat
share .. tomcat
tomcat .. repojava
search .. searchjava
transform .. transformjava
sync .. syncjava
amq .. amqjava

Client --> proxy

proxy --> repo
proxy --> share
proxy --> adw

share -right-> repo
adw --> repo

repo --> psql
repo --> transform
repo --> amq
repo <--> search
repo <--> sync

transform --> amq

sync --> amq
sync --> psql

center footer Copyright 2020 Alfresco Software Inc

@enduml
