@startuml deployment-type-ssh

Title: SSH Deployment

skinparam componentStyle uml2
skinparam linetype ortho

actor User

node "Control Node" as "control" #LightGrey {
    rectangle "Playbook" as playbook #Ivory
    rectangle "inventory" #White
}

node "Target Host 1" as host1 #LightGrey {
    component role1 as host1role1 #4d9cea {
        node "task" as host1role1task1 #Wheat
        node "task" as host1role1task2 #Wheat
    }
}

node "Target Host 2" as host2 #LightGrey {
    component role2 as host2role2 #4d9cea {
        node "task" as host2role2task1 #Wheat
        node "task" as host2role2task2 #Wheat
    }
}

User -> playbook
playbook <- inventory
playbook -down-> host1role1 : ssh
playbook -down-> host2role2 : ssh


@enduml